import { readFileSync } from "node:fs";
import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import icon from "astro-icon";
import tailwindcss from "@tailwindcss/vite";

const SITE = "https://__DOMAIN__";

// lastmod dates from git history, pre-generated by scripts/generate-sitemap-dates.js
// and committed so shallow-clone CI builds get accurate dates.
const sitemapDates: Record<string, string> = JSON.parse(
  readFileSync(new URL("./generated/sitemap-dates.json", import.meta.url), "utf-8")
);

const ROUTE_META: Record<string, { changefreq: string; priority: number }> = {
  "/": { changefreq: "weekly", priority: 1.0 },
  "/about": { changefreq: "monthly", priority: 0.5 },
  "/tos": { changefreq: "yearly", priority: 0.3 },
  "/privacy-policy": { changefreq: "yearly", priority: 0.3 },
};

export default defineConfig({
  site: SITE,
  trailingSlash: "never",
  // 'file' emits about.html (not about/index.html) so Cloudflare serves /about
  // without a trailing-slash redirect — exact parity with the old Next export.
  build: { format: "file" },
  integrations: [
    icon({ include: { lucide: ["*"] } }),
    sitemap({
      serialize(item) {
        const path = new URL(item.url).pathname.replace(/\/$/, "") || "/";
        const meta = ROUTE_META[path] ?? { changefreq: "monthly", priority: 0.5 };
        return {
          ...item,
          // Root canonical is https://__DOMAIN__ without trailing slash (live parity).
          url: path === "/" ? SITE : `${SITE}${path}`,
          lastmod: sitemapDates[path] ?? new Date().toISOString(),
          changefreq: meta.changefreq as never,
          priority: meta.priority,
        };
      },
    }),
  ],
  vite: {
    // Cast: @tailwindcss/vite ships its own vite types that clash with astro's nested vite.
    plugins: [tailwindcss() as never],
  },
});
